---
docker_distro: "{{ ansible_facts['distribution'] | lower }}"
docker_release: "{{ ansible_facts['distribution_release'] }}"
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
# Pakete der Distribution, die mit Docker CE kollidieren
docker_conflicting_packages:
  - docker.io
  - docker-doc
  - docker-compose
  - docker-compose-v2
  - podman-docker
  - containerd
  - runc
docker_log_max_size: 10m
docker_log_max_file: 3
