---
- name: Update apt-get repo and cache
  hosts: all
  become: true
  tasks:
    - name: Update all packages
      apt: 
        upgrade: yes
        update_cache: yes
    - name: Check if a reboot is needed for Debian and Ubuntu boxes
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no