- name: Send ntfy.sh message
  hosts: all
  tasks:
    - name: send POST message
      uri:
        url: "https://ntfy.qp8.de/{{ ntfy_channel }}"
        method: POST
        body: "Test reseeding complete"